### ISSUE TITLE
Example in readme doesn't work

### ISSUE THREAD

**Issue by DePasqualeOrg** [immers-space/activitypub-express#54]
When I try using the example code from the readme, I get the following error:

```
/<redacted>/index.js:35
app.use(express.json({ type: apex.consts.jsonldTypes }), apex);
                                         ^

TypeError: Cannot read properties of undefined (reading 'jsonldTypes')
    at Object.<anonymous> (/<redacted>/index.js:35:42)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by wmurphyrd** [comment]
Thanks for the report. Could you show me how you define the `apex` variable?

We have this code in our [unit tests](https://github.com/immers-space/activitypub-express/blob/master/spec/helpers/test-utils.js#L47) and [applications](https://github.com/wmurphyrd/guppe/blob/main/index.js#L52) working ok.

**Comment by DePasqualeOrg** [comment]
[Here](https://gist.github.com/DePasqualeOrg/b04df336ddcf82ed0da06598a241d5a7) is the code I'm using.

**Comment by wmurphyrd** [comment]
Thanks for sharing! You have a very old version of `activitypub-express` installed - 0.0.2 and a newer version of mongo (we're working on updating the mongo dependency). Change your dependencies as follows, `npm install`, and it will run:

```
  "dependencies": {
    "activitypub-express": "^2.3.0",
    "express": "^4.17.2",
    "mongodb": "^3.6.3"
  }
```

Curious how you ended up with that version - did it come from some documentation I need to update?

**Comment by DePasqualeOrg** [comment]
Yeah, that's strange. That's the version that was installed when I ran `npm i activitypub-express` this morning. When I reinstalled it, it installed the latest version. I think I also ran `npm audit fix --force` after installing the first time. Perhaps the version got changed after that.

I changed the dependencies as you suggested, and I no longer get an error. Thanks for your help!

**Comment by DePasqualeOrg** [comment]
Actually, I spoke too soon. Now I'm getting the following error:

```
/<redacted>/node_modules/mongodb/lib/core/sdam/topology.js:438
        const timeoutError = new MongoServerSelectionError(
                             ^

MongoServerSelectionError: connect ECONNREFUSED ::1:27017
    at Timeout._onTimeout (/<redacted>/node_modules/mongodb/lib/core/sdam/topology.js:438:30)
    at listOnTimeout (node:internal/timers:568:17)
    at processTimers (node:internal/timers:510:7) {
  reason: TopologyDescription {
    type: 'Single',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map(1) {
      'localhost:27017' => ServerDescription {
        address: 'localhost:27017',
        error: Error: connect ECONNREFUSED ::1:27017
            at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
          name: 'MongoNetworkError'
        },
        roundTripTime: -1,
        lastUpdateTime: 1714737724,
        lastWriteDate: null,
        opTime: null,
        type: 'Unknown',
        topologyVersion: undefined,
        minWireVersion: 0,
        maxWireVersion: 0,
        hosts: [],
        passives: [],
        arbiters: [],
        tags: []
      }
    },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
}
```
