### ISSUE TITLE
An error occurred while processing (/outbox?page) request

### ISSUE THREAD

**Issue by LuckyCoders** [immers-space/activitypub-express#91]
```
| Unrecognized or invalid _bsontype: ObjectID {} BSONError: Unrecognized or invalid _bsontype: ObjectID
|     at serializeInto (/var/www/r/node_modules/bson/lib/bson.cjs:3678:23)
|     at serializeObject (/var/www/r/node_modules/bson/lib/bson.cjs:3199:22)
|     at serializeInto (/var/www/r/node_modules/bson/lib/bson.cjs:3633:25)
|     at serializeObject (/var/www/r/node_modules/bson/lib/bson.cjs:3199:22)
|     at serializeInto (/var/www/r/node_modules/bson/lib/bson.cjs:3633:25)
|     at serializeObject (/var/www/r/node_modules/bson/lib/bson.cjs:3199:22)
|     at serializeInto (/var/www/r/node_modules/bson/lib/bson.cjs:3432:25)
|     at serializeObject (/var/www/r/node_modules/bson/lib/bson.cjs:3199:22)
|     at serializeInto (/var/www/r/node_modules/bson/lib/bson.cjs:3633:25)
|     at Object.serialize (/var/www/r/node_modules/bson/lib/bson.cjs:4017:32)
```

**Comment by LuckyCoders** [comment]
error in store/index.js
```
const result = this.db.collection('streams').aggregate(pipeline)
return **result.toArray()**
```

**Comment by LuckyCoders** [comment]
downgrade `mongodb` to 4.16.0 helps.
`npm install mongodb@4.16.0`

**Comment by LuckyCoders** [comment]
> 
db version v6.0.2
